const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{let b;try{b=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const ctx=await b.newContext({acceptDownloads:true});const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));const url='file://'+path.resolve(process.argv[2]||'output','index.html');await p.goto(url);await p.waitForTimeout(500);console.log('errors',errs);assert.deepEqual(errs,[]);
await p.locator('#transcript-L1 > summary').click();await p.locator('[data-edit-blanks]').click();await p.locator('#blankText0').evaluate(t=>t.setSelectionRange(3,9));await p.locator('[data-add-blank="0"]').click();await p.locator('#saveTeacherBlanks').click();assert.equal(await p.evaluate(()=>sections.get('L1').blanks.length),2);
await p.reload();assert.equal(await p.evaluate(()=>sections.get('L1').blanks.length),2);
assert(await p.evaluate(()=>{try{checkedTeacherBlanks(sections.get('L1'),[{paragraph_id:'L1-p1',start:9999,end:10000,quote:'x'}]);return false}catch{return true}}));
await p.evaluate(()=>{saveSession();const record=JSON.parse(localStorage.getItem(saveKey));applyTeacherBlanks({L1:[]});restoreRecord(record)});assert.equal(await p.evaluate(()=>sections.get('L1').blanks.length),2);

await p.locator('.listen-play').first().click();await p.waitForTimeout(500);assert(await p.evaluate(()=>document.querySelector('#audio-L1').currentTime>0));await p.locator('.listen-play').first().click();
const dl=p.waitForEvent('download');await p.locator('#exportPortableLesson').click();const d=await dl;const dest=path.resolve(process.argv[2]||'output','..','standalone.html');await d.saveAs(dest);
const isolated=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const phone=await isolated.newPage();phone.on('pageerror',e=>errs.push(e.message));await phone.goto('file://'+dest);assert.equal(await phone.evaluate(()=>sections.get('L1').blanks.length),2);await phone.locator('.listen-play').first().tap();await phone.waitForTimeout(500);assert(await phone.evaluate(()=>document.querySelector('#audio-L1').currentTime>0));assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await phone.locator('#boardMode').tap();assert(await phone.locator('body').evaluate(e=>e.classList.contains('touch-board')));assert.deepEqual(errs,[]);for(const size of [{width:820,height:1180},{width:1920,height:1080}]){await phone.setViewportSize(size);assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}await phone.screenshot({path:path.resolve(process.argv[2]||'output','phone.png')});console.log('PASS blank edit/reload/export; standalone audio; touch phone layout; board mode');}finally{if(b)await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
