#!/usr/bin/env node
/* Actual browser interaction checks; no dependency installation or network services. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const out=path.resolve(process.argv[2]||'output'),stress=process.argv.includes('--stress');
const report={status:'running',html_sha256:null,engine:process.env.BROWSER_ENGINE||'chromium',checks:[],errors:[],scope:'Actual clicks and media playback via localhost; not a WorkBuddy/Doubao end-to-end certification, file:// test, or teaching/audio-alignment review.'};
let server,browser;
const save=()=>fs.writeFileSync(path.join(out,'browser-check.json'),JSON.stringify(report,null,2));
const ok=(name,details)=>{report.checks.push({name,status:'passed',details});console.log('PASS '+name)};
const deadline=setTimeout(()=>{report.status='failed';report.errors.push('Browser check exceeded 180 seconds.');save();process.exit(1)},180000);
async function main(){
 const html=fs.readFileSync(path.join(out,'index.html'));report.html_sha256=crypto.createHash('sha256').update(html).digest('hex');
 const match=html.toString().match(/<script id="examData" type="application\/json">([\s\S]*?)<\/script>/);assert.ok(match,'Missing canonical examData');const exam=JSON.parse(match[1]);
 let pw;try{pw=require(process.env.PLAYWRIGHT_MODULE||'playwright')}catch{report.status='not_available';throw Error('Playwright 未安装；没有自动安装。可使用宿主浏览器逐项验收并记录，或经同意准备浏览器测试环境。')}
 server=http.createServer((req,res)=>{try{const url=new URL(req.url,'http://localhost');const isolated=url.pathname==='/isolated.html';let file=isolated?path.join(out,'index.html'):path.resolve(out,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));if(file!==out&&!file.startsWith(out+path.sep)){res.writeHead(403).end();return}const bytes=fs.readFileSync(file),ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.json':'application/json','.wav':'audio/wav','.mp3':'audio/mpeg','.png':'image/png','.jpg':'image/jpeg'})[ext]||'application/octet-stream');res.setHeader('Cache-Control','no-store');const range=req.headers.range?.match(/^bytes=(\d+)-(\d*)$/);if(range){const start=+range[1],end=Math.min(range[2]?+range[2]:bytes.length-1,bytes.length-1);if(start>end){res.writeHead(416).end();return}res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${bytes.length}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});res.end(bytes.subarray(start,end+1))}else res.end(bytes)}catch{res.writeHead(404).end()}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
 browser=await pw[report.engine].launch({headless:true,...(process.env.CHROME_BIN?{executablePath:process.env.CHROME_BIN}:{})});report.browser_version=browser.version();report.platform=process.platform;
 async function newPage(mode='normal',width=1440){const ctx=await browser.newContext({viewport:{width,height:900},javaScriptEnabled:mode!=='no-js'});await ctx.route('**/*',route=>route.request().url().startsWith(base)||route.request().url().startsWith('data:')?route.continue():route.abort());
 if(mode==='isolated')await ctx.route('**/audio/**',r=>r.abort());
 await ctx.addInitScript(({mode,title})=>{
 if(mode==='no-speech'){Object.defineProperty(window,'speechSynthesis',{value:undefined});Element.prototype.requestFullscreen=undefined}
 if(mode==='no-canvas')HTMLCanvasElement.prototype.getContext=()=>null;
 if(mode==='no-dialog'){HTMLDialogElement.prototype.showModal=undefined;HTMLDialogElement.prototype.close=undefined}
 if(mode==='bad-scores')localStorage.setItem('exam-scores-'+title,'[null,null,null,null]');
 if(mode==='bad-storage')localStorage.setItem('exam-classroom-v5-'+title,JSON.stringify({title,version:5,ui:{openAnswers:null,layout:null}}));
 if(mode==='no-storage'){Storage.prototype.getItem=()=>{throw Error('Storage blocked')};Storage.prototype.setItem=()=>{throw Error('Storage blocked')}}
 },{mode,title:exam.title});const p=await ctx.newPage();p.setDefaultTimeout(7000);p.on('pageerror',e=>report.errors.push(mode+': '+e.message));await p.goto(base+(mode==='isolated'?'/isolated.html':'/'),{waitUntil:'load',timeout:15000});if(mode!=='no-js')await p.waitForFunction(()=>window.__lessonReady===true,{},{timeout:10000});return {p,ctx}}
 async function go(p,s){await p.locator(`[data-group="${s.kind}"] .chapter-group-toggle`).click();await p.locator(`#chapterMenuFloat [data-nav="${s.id}"]`).click();await p.waitForFunction(id=>state.active===id,s.id);}
 async function quick(p){const count=exam.sections.filter(s=>s.kind!=='writing').reduce((n,s)=>n+s.questions.length,0);if(!count)return;await p.locator('#quickAnswers').click();assert.equal(await p.locator('.answer-tile').count(),count);await p.locator('#quickToggleAnswers').click();await p.locator('#quickScopeKind').click();const kinds=[...new Set(exam.sections.filter(s=>s.kind!=='writing').map(s=>s.kind))];assert.equal(await p.locator('#quickAnswerScope option').count(),kinds.length);for(const k of kinds){await p.locator('#quickAnswerScope').selectOption(k);assert.equal(await p.locator('.answer-tile').count(),exam.sections.filter(s=>s.kind===k).reduce((n,s)=>n+s.questions.length,0))}await p.locator('[data-close="quickAnswersDialog"]').click()}
 async function play(p,s){await go(p,s);const a=p.locator('#audio-'+s.id);await a.evaluate(a=>a.muted=true);await p.locator(`[data-action="playListening"][data-sid="${s.id}"]`).click();await p.waitForFunction(id=>{const a=document.getElementById('audio-'+id);return a.currentTime>0&&!a.paused},s.id);assert.ok(await a.evaluate(a=>Number.isFinite(a.duration)&&a.duration>0));await p.locator(`.speed[data-audio="audio-${s.id}"]`).selectOption('0.75');assert.equal(await a.evaluate(a=>a.playbackRate),.75);await p.locator(`[data-action="playListening"][data-sid="${s.id}"]`).click();for(const q of s.questions.filter(q=>q.audio)){const qa=p.locator(`audio[data-q-audio="${q.id}"]`);await qa.evaluate(async a=>{a.muted=true;await a.play()});await p.waitForFunction(id=>document.querySelector('audio[data-q-audio="'+id+'"]').currentTime>0,q.id);await qa.evaluate(a=>a.pause())}}
 const {p,ctx}=await newPage();assert.ok(await p.locator('#bootNotice').isHidden());assert.equal(await p.locator('.chapter-group-toggle').count(),new Set(exam.sections.map(s=>s.kind)).size);
 for(const s of exam.sections){await go(p,s);const section=p.locator('#section-'+s.id);assert.ok(await section.isVisible());if(s.kind==='listening')assert.match(await section.locator('h2').innerText(),/^Test /);else{const t=section.locator('[data-action="translate"]').first();if(await t.count()){await t.click();assert.ok(await section.locator('.translation:not([hidden])').count()>0);await t.click()}}
 await section.locator('[data-action="vocabulary"]').click();assert.ok(await p.locator('#studyDialog').isVisible());await p.locator('[data-close="studyDialog"]').click();
 // Each question is independently expandable; no whole-section reveal substitution.
 for(const q of s.questions){const button=section.locator(`[data-action="answer"][data-qid="${q.id}"]`);if(await button.count()){await button.click();assert.ok(await p.evaluate(id=>ui.openAnswers.includes(id),q.id));await button.click()}}
 }
 ok('all-sections-navigation-vocabulary-and-individual-analysis',{sections:exam.sections.length,questions:exam.sections.reduce((n,s)=>n+s.questions.length,0)});
 assert.equal(await p.locator('#themeSelect option').count(),6);for(const theme of ['paper','amethyst','mist','sand','rose','pearl']){await p.locator('#themeSelect').selectOption(theme);assert.equal(await p.locator('#themeSelect').inputValue(),theme)}await p.locator('#themeSelect').selectOption('amethyst');await p.locator('#fontSizeSelect').selectOption('28');await p.reload();await p.waitForFunction(()=>window.__lessonReady);assert.equal(await p.locator('#fontSizeSelect').inputValue(),'28');assert.equal(await p.locator('#themeSelect').inputValue(),'amethyst');ok('font-and-theme-persist');
 const before=await p.evaluate(()=>JSON.stringify([ui.openAnswers,[...state.answers]]));await quick(p);assert.equal(await p.evaluate(()=>JSON.stringify([ui.openAnswers,[...state.answers]])),before);ok('quick-answers-whole-and-kind-no-analysis-side-effects');
 const reading=exam.sections.find(s=>s.kind==='reading')||exam.sections.find(s=>s.kind!=='listening');if(reading)await go(p,reading);
 await p.locator('#annotate').click();assert.ok(await p.locator('#inkToolbar').isVisible());
 if(reading){const box=await p.locator('#section-'+reading.id+' .source-text').first().boundingBox();assert.ok(box);for(const tool of ['pen','arrow','rect','ellipse']){await p.locator('[data-ink-mode="'+tool+'"]').click();await p.mouse.move(box.x+20,box.y+15);await p.mouse.down();await p.mouse.move(box.x+140,box.y+55,{steps:8});await p.mouse.up()}assert.equal(await p.evaluate(()=>ui.ink[state.active].length),4);await p.locator('#inkUndo').click();assert.equal(await p.evaluate(()=>ui.ink[state.active].length),3);await p.locator('#inkClear').click();assert.equal(await p.evaluate(()=>ui.ink[state.active].length),0);ok('pen-arrow-rectangle-ellipse-undo-clear')}
 await p.locator('#inkClose').click();await p.locator('#classroom').click();assert.ok(await p.locator('#classDialog').isVisible());await p.locator('[data-close="classDialog"]').click();ok('annotation-and-classroom-open');
 const listening=exam.sections.find(s=>s.kind==='listening'&&s.audio);if(listening){for(const s of exam.sections.filter(s=>s.kind==='listening'&&s.audio))await play(p,s);ok('listening-and-question-media-play-and-speed');}
 for(const width of [1024,390]){await p.setViewportSize({width,height:900});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await go(p,exam.sections[0]);await quick(p)}ok('narrow-screen-navigation-and-dialogs');await ctx.close();
 if(listening&&Object.keys(exam._embedded_audio||{}).length){const x=await newPage('isolated');await play(x.p,listening);await x.ctx.close();ok('embedded-audio-with-external-audio-blocked')}
 if(stress){for(const mode of ['no-speech','bad-storage','no-storage','no-dialog','no-canvas','bad-scores']){const x=await newPage(mode);await go(x.p,exam.sections.at(-1));await quick(x.p);await x.p.locator('#classroom').click();assert.ok(await x.p.locator('#classDialog').isVisible());await x.p.locator('#minutes').fill('2');assert.ok(await x.p.locator('#classDialog').isVisible());await x.p.locator('[data-close="classDialog"]').click();if(mode==='no-speech')await x.p.locator('#fullScreen').click();await x.ctx.close();ok('recovery-'+mode)}const x=await newPage('no-js');assert.ok(await x.p.locator('#bootNotice').isVisible());assert.match(await x.p.locator('#bootNotice').innerText(),/下载完整课件 ZIP/);await x.ctx.close();ok('script-disabled-static-opening-guide')}
 assert.deepEqual(report.errors,[],'Browser runtime errors');report.status='passed';
}
main().catch(e=>{if(report.status!=='not_available')report.status='failed';report.errors.push(e.stack||String(e));console.error(e.message);process.exitCode=1}).finally(async()=>{clearTimeout(deadline);try{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r))}finally{if(fs.existsSync(out))save()}});
